// const REBOOT_INITIATED = 'REBOOT_INITIATED';
// const REBOOT_DETECTED_UNDERWAY = 'REBOOT_DETECTED_UNDERWAY';
// const REBOOT_RESOLVED = 'REBOOT_RESOLVED';

// export default { REBOOT_INITIATED, FINISH_REBOOOT, REBOOT_RESOLVED };